import type { Metadata } from 'next'
import { poppins } from '../components/ui/fonts'

import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Page from '@/components/layout/Page'
import Projetos from './projetos/page'
import Home from './page'
import { Router, useLocation, useRoutes } from 'react-router-dom'
import { AnimatePresence } from 'framer-motion'
import React from 'react'
import TemplateTransition from '@/components/layout/Transition'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`min-h-screen h-full ${poppins.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Page>
            <TemplateTransition>
              {children}
            </TemplateTransition>
          </Page>
        </ThemeProvider>
      </body>
    </html>
  )
}
